# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de1049653f869bc62a2a6e9cf2a32bfc8377fa724914159c9b31e5a8c3a2a2f04c9040645239d399a5dfc0e7ba620cff9cdff8c6b4531538ae5af2fc36b5ee1

test:
  secret_key_base: e5459d2062044ac5c4adfb192da9b3631c9d11fb084b9ac7480e2c8f45cb8f558b27b1542763cbb3468553585152b5671612f8e6f69b9a96abad7a88bcf43adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
